# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(caret)
}
b <- board_folder(path = "/kaggle/working/outputs")
v <- vetiver_pin_read(b, "accident_model", version = "20231021T025821Z-51e08")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
